### ISSUE TITLE
NullPointerException CloudFoundryServiceInfoCreator

### ISSUE THREAD

**Issue by jonnybbb** [spring-cloud/spring-cloud-connectors#100]
Using the Stackato filesystem Service causes a NPE. 

```
[app] 2015-02-04T16:45:59.000Z: to/app/lib/spring-expression-4.1.4.RELEASE.jar!/]
[app] 2015-02-04T16:45:59.000Z: 2015-02-04 08:45:59,059 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
[app] 2015-02-04T16:45:59.000Z: java.lang.NullPointerException: null
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.getStringFromCredentials(CloudFoundryServiceInfoCreator.java:94) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.getUriFromCredentials(CloudFoundryServiceInfoCreator.java:89) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.uriMatchesScheme(CloudFoundryServiceInfoCreator.java:46) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.accept(CloudFoundryServiceInfoCreator.java:26) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.accept(CloudFoundryServiceInfoCreator.java:15) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfo(AbstractCloudConnector.java:60) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfos(AbstractCloudConnector.java:40) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceInfos(Cloud.java:92) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getCloudProperties(Cloud.java:221) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer.addCloudPropertySource(CloudPropertySourceApplicationContextInitializer.java:83) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
[app] 2015-02-04T16:45:59.000Z: at org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer.initialize(CloudPropertySourceApplicationContextInitializer.java:67) ~[spring_auto_reconfiguration-1.7.0_RELEASE.jar:na]
```

The service has the following settings:
```
System-Provided:
{
  "VCAP_SERVICES": {
    "filesystem-1.0": [
      {
        "credentials": {
          "dir": "/var/stackato/services/filesystem/storage/stackatofs-9c5499bf1756580/storage",
          "host": "10.0.1.115",
          "hostname": "10.0.1.115",
          "name": "9c5499bf1756580",
          "private_key": "-----BEGIN RSA PRIVATE KEY----- .... -----END RSA PRIVATE KEY-----\n",
          "user": "stackatofs-9c5499bf1756580"
        },
        "label": "filesystem-1.0",
        "name": "lucene-service-fs",
        "plan": "free",
        "tags": []
      }
    ],

```
With previous versions provided by the [Java Buildpack](https://github.com/cloudfoundry/java-buildpack) the error did not occur

**Comment by scottfrederick** [comment]
@jonnybbb We are looking into what's going on here. It is not obvious from the code why that `NullPointerException` is getting thrown when trying to de-reference the `credentials` hash, even though that hash exists in your `VCAP_SERVICES`. 

In your stack trace, spring-cloud-connectors is actually being shaded into the [Java buildpack auto-reconfiguration support library](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration), which might have something to do with the issue.

**Comment by scottfrederick** [comment]
@jonnybbb If this is still a problem, please create an issue in the [Java buildpack auto-reconfiguration support library](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/issues) repo, since this looks like it has to do with how that library shades in spring-cloud-connectors, not in this library itself.
