### ISSUE TITLE
Missing constructor "public CloudFoundryServiceInfoCreator(String tag)" is breaking compatibility with cloudfoundry-ups-connector

### ISSUE THREAD

**Issue by raphsoft** [spring-cloud/spring-cloud-connectors#158]
As far as I know latest version of UPS connector is: 0.9.10.RELEASE and it depends on spring-cloud-cloudfoundry-connector (previously known as cloud-cloudfoundry-connector).

This [class](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/CloudFoundryServiceInfoCreator.java) had a constructor taking only one string parameter but it was deleted.

As ups-connector is used to bind rabbitmq services to applications and it seems not to be opensource (I didn't find anything on github) the removed method is causing the ups-connector to fail when trying to instantiate UserProvidedRabbitServiceInfoCreator:

```
  public UserProvidedRabbitServiceInfoCreator()
  {
    super("amqp:");
  }
  
```

Is there a workaround for it other than creating a custom service connector? This is the log when you have ups-connector added as a dependency using the latest connector (in our case we need the spring-cloud-cloudfundry-connector version 1.2.0 as a dependency for sso-connector 1.1.0)

```
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.cloudfoundry.RelationalServiceInfoCreator.<init>(Ljava/lang/String;)V
        at org.springframework.cloud.cloudfoundry.UserProvidedRelationalServiceInfoCreator.<init>(UserProvidedRelationalServiceInfoCreator.java:11) ~[cloudfoundry-ups-connector-0.9.10.RELEASE.jar:na]
        at org.springframework.cloud.cloudfoundry.UserProvidedMysqlServiceInfoCreator.<init>(UserProvidedMysqlServiceInfoCreator.java:7) ~[cloudfoundry-ups-connector-0.9.10.RELEASE.jar:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_71]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_71]
        at sun.reflect.DelegatingConstructorAccel.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_71]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_71]
        at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_71]
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_71]
        ... 40 common frames omitted

```

**Comment by scottfrederick** [comment]
The ups-connector was deprecated long ago. The spring-cloud-cloudfoundry-connector supports user-provided service instances by inspecting the `url` or `uri` field in the credentials and looking at the URL scheme. 

A user-provided service instance created like this: 

`$ cf cups rabbitmq -p '{"uri":"amqp://test:test@192.168.1.63/"}'`

would be detected by spring-cloud-cloudfoundry-connector based on the `amqp` scheme in the `uri` field.
