### ISSUE TITLE
CloudFoundryConnector throws NullPointerException when VCAP_SERVICES is null

### ISSUE THREAD

**Issue by brian-l-coker** [spring-cloud/spring-cloud-connectors#178]
When VCAP_SERVICES is null, the CloudFoundryConnector invokes the ObjectMapper even when VCAP_SERVICES is null or empty. The net result is a NullPointerException. I believe there should be an else block around lines 73-77.

```
Caused by: java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_66]
	at org.springframework.cloud.cloudfoundry.com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:835) ~[spring-cloud-cloudfoundry-connector-1.2.3.RELEASE.jar:?]
	at org.springframework.cloud.cloudfoundry.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098) ~[spring-cloud-cloudfoundry-connector-1.2.3.RELEASE.jar:?]
	at org.springframework.cloud.cloudfoundry.CloudFoundryConnector.getServicesData(CloudFoundryConnector.java:74) ~[spring-cloud-cloudfoundry-connector-1.2.3.RELEASE.jar:?]
	at org.springframework.cloud.AbstractCloudConnector.getServiceInfos(AbstractCloudConnector.java:39) ~[spring-cloud-core-1.2.3.RELEASE.jar:?]
	at org.springframework.cloud.Cloud.getServiceInfos(Cloud.java:89) ~[spring-cloud-core-1.2.3.RELEASE.jar:?]
	at org.springframework.cloud.Cloud.getServiceInfo(Cloud.java:76) ~[spring-cloud-core-1.2.3.RELEASE.jar:?]
```

**Comment by scottfrederick** [comment]
Fixed via ff2b601d18cf5f3779014599836c339551e21cc9
