### ISSUE TITLE
Upgrade connectors for Spring Data Kay 2.0

### ISSUE THREAD

**Issue by mp911de** [spring-cloud/spring-cloud-connectors#195]
Spring Data 2.0, especially MongoDB, introduces a series of breaking changes that require adoption in Spring Cloud Connectors 2.0

Example stack trace for Spring Boot 2.0 with Spring Data MongoDB 2.0:
```
org.cloudfoundry.reconfiguration.spring.AbstractCloudServiceBeanFactoryPostProcessor.reconfigureBean(AbstractCloudServiceBeanFactoryPostProcessor.java:119) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context-5.0.0.BUILD-SNAPSHOT.jar!/:5.0.0.BUILD-SNAPSHOT]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:49) ~[spring-boot-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.document.MongoDbFactoryCreator.createMongoDbFactory(MongoDbFactoryCreator.java:50) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.spring.AbstractCloudServiceBeanFactoryPostProcessor.processBean(AbstractCloudServiceBeanFactoryPostProcessor.java:112) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.spring.AbstractCloudServiceBeanFactoryPostProcessor.processBeans(AbstractCloudServiceBeanFactoryPostProcessor.java:97) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.spring.AbstractCloudServiceBeanFactoryPostProcessor.postProcessBeanFactory(AbstractCloudServiceBeanFactoryPostProcessor.java:63) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] 2017-04-19 07:51:12.543 ERROR 14 --- [ main] o.s.boot.SpringApplication : Application startup failed
2017-04-19T09:51:12.544+02:00 [APP/PROC/WEB/0] [OUT] java.lang.NoSuchMethodError: org.springframework.data.mongodb.core.SimpleMongoDbFactory.<init>(Lcom/mongodb/Mongo;Ljava/lang/String;)V
```

**Comment by scottfrederick** [comment]
@mp911de This should be addressed in the [`2.x` branch](https://github.com/spring-cloud/spring-cloud-connectors/tree/2.x) of this repo, which is currently being deployed as `2.0.0.BUILD-SNAPSHOT` in [repo.spring.io/libs-snapshot](https://repo.spring.io/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/springframework/cloud/spring-cloud-cloudfoundry-connector/2.0.0.BUILD-SNAPSHOT). Can you verify that this version works as expected?

**Comment by mp911de** [comment]
I created the ticket more as a reminder for me to submit a PR if necessary. Will take a look into it.

**Comment by mp911de** [comment]
Redis (lettuce) requires an upgrade to use `io.lettuce:lettuce-core:5.0.x` because lettuce changed groupId/ArtifactId. I'll send a PR once I was able to release a non-snapshot version of lettuce. I verified interoperability with MongoDB using Boot 2.0/Cloud Connectors 2.0 (Snapshots).

**Comment by scottfrederick** [comment]
Awesome, thanks @mp911de.

**Comment by wilkinsona** [comment]
This is current breaking the Platform's compatibility builds as Spring Boot 2.0 snapshots have moved to Lettuce 5.0.0.BUILD-SNAPSHOT to align with the latest Spring Data Redis snapshots. Could Spring Cloud Connector snapshots please follow suit?

**Comment by mp911de** [comment]
@wilkinsona I started with a PR and want to publish a non-snapshot version of lettuce within the next few days to not depend on Sonatype's OSS snapshot repo.

**Comment by wilkinsona** [comment]
What's the problem with depending on Sonatype's OSS snapshot repo? As things stand we have a collection of snapshots that don't work together. I guess it's ok if it's only going to be a few days, but I do wonder if it might not be easier to move SCC onto snapshots now so that it's aligned with the latest Boot and Data Redis snapshots.

**Comment by mp911de** [comment]
@scottfrederick your call. I'm fine either way. Just didn't want to introduce dependencies to repositories that weren't there in the first place.

**Comment by scottfrederick** [comment]
Adding a snapshot repo on the 2.x branch is fine. We have spring snapshot
repos there already.

I can merge a PR as soon as you have one ready.

**Comment by scottfrederick** [comment]
@mp911de @wilkinsona I think this issue is fixed in the 2.x branch. Please comment and reopen if you know of anything that still needs to be done.
