### ISSUE TITLE
Binding to a DB with a Password that contains a `%` causes `java.net.URISyntaxException: Malformed escape pair at index 92`

### ISSUE THREAD

**Issue by jzingler** [spring-cloud/spring-cloud-connectors#213]
I am working through an issue trying to bind a User Provided service for a Microsoft SQL Server instance.  The password for the Microsoft SQL server contains a special character `%` which appears to be the cause of the issue.  

The UriInfo.getUri() method does not encode the db uri before attempting to create a URI. To handle percentages within passwords, I believe we would need to encode on creation of URI and decode for initiating the connection to the DB. 

```
2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT Caused by: java.net.URISyntaxException: Malformed escape pair at index 92: jdbc:sqlserver://<host><:PORT>;database=<db>;user=<user>;password=<special chars in password>
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at java.net.URI$Parser.fail(URI.java:2848)
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at java.net.URI$Parser.scanEscape(URI.java:2978)
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at java.net.URI$Parser.scan(URI.java:3001)
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at java.net.URI$Parser.checkChars(URI.java:3019)
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at java.net.URI$Parser.parse(URI.java:3058)
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at java.net.URI.<init>(URI.java:588)
   2017-09-12T11:30:34.70-0500 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.getUri(UriInfo.java:95)
```

**Comment by fpestke** [comment]
I had the same issue with a Postgres database and think the error is caused by `RelationalServiceInfo.formatUserInfo` because username and password need to be url encoded before adding to the jdbc url.

**Comment by scottfrederick** [comment]
@jzingler @fpestke 

> I believe we would need to encode on creation of URI and decode for initiating the connection to the DB.

I'm concerned about making a change for this issue without having a reliable test case for it. Specifically, I'm not sure where the "decode for initiating the connection" would happen, or how the database drivers and backend dbs would handle a URL with a password that's been URL-encoded. Can you provide an example of a `VCAP_SERVICES` payload that demonstrates the problem, and a JDBC connection string containing a password that the driver and db is happy with?

**Comment by anwarchk** [comment]
@jzingler can you please provide the requested info to @scottfrederick ?
