### ISSUE TITLE
Tests failures with Cassandra Driver 3.3.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-connectors#215]
Spring Data Cassandra 2.0.0 uses Cassandra Driver 3.3.0. When Spring Cloud Connectors is tested against this version combination, 6 tests fail:

- CassandraClusterFactoryJavaConfigTest.cloudRedisConnectionFactoryConfig
- CassandraClusterXmlConfigTest.cassandraSessionWithConfiguration
- CassandraClusterXmlConfigTest.cloudConnectorWithServiceNameSpecified_TwoServiceExist
- CassandraClusterXmlConfigTest.cloudConnectorWithServiceNameSpecified_UniqueServiceExists
- CassandraClusterXmlConfigTest.cloudConnectorWithoutServiceNameSpecified_UniqueServiceExists
- CloudAllServicesTest. allServicesProvisioned

The root cause for each failure appears to be the same NPE:

```
Caused by: java.lang.NullPointerException
	at com.datastax.driver.core.Cluster$Builder.withProtocolVersion(Cluster.java:839)
	at org.springframework.cloud.service.column.CassandraClusterCreator.create(CassandraClusterCreator.java:64)
	at org.springframework.cloud.service.column.CassandraClusterCreator.create(CassandraClusterCreator.java:34)
	at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:245)
	at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:133)
	at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createService(AbstractCloudServiceConnectorFactory.java:105)
	at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createInstance(AbstractCloudServiceConnectorFactory.java:99)
	at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:141)
	at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.afterPropertiesSet(AbstractCloudServiceConnectorFactory.java:94)
	at org.springframework.cloud.config.xml.CloudServiceIntroducer.postProcessBeanFactory(AbstractCloudServiceFactoryParser.java:82)
	... 54 more
```

**Comment by wilkinsona** [comment]
The failures can be reproduced by running the following command (updated as necessary to match the location of your JDK 8 installation) in the 2.x branch:

```
./gradlew clean springIoCheck -PJDK8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home -PplatformVersion=Cairo-BUILD-SNAPSHOT --continue
```
