### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/dbcp2/BasicDataSource

### ISSUE THREAD

**Issue by mortenri** [spring-cloud/spring-cloud-connectors#236]
Hi,

We updated our project from Spring Boot .5.15.RELEASE to 2.0.6.RELEASE and Spring Framework from 4.3.18.RELEASE to 5.1.1.RELEASE. We are also using javax.persistence (2.0.4.v201112161009), eclipselink (2.5.2)and liquibase (3.5.3). The service is bound to one postgresql services. As soon as I push the application to cloud foundry we are facing the following error:

- java.lang.NoClassDefFoundError: org/apache/commons/dbcp2/BasicDataSource

I tried turning off the autoconfiguration without access. I used the following annotation:

@SpringBootApplication (exclude={DataSourceAutoConfiguration.class,HibernateJpaAutoConfiguration.class,DataSourceTransactionManagerAutoConfiguration.class })

Is there any know issue that the datasource always gets loaded even if I don't want spring to?

I could just add a dependency to tomcat-dbcp and the issue is gone but then still a datasource is configured for me. I rechecked the log statements of our project with old dependencies mentioned above and found the following log entry:
-    o.s.c.s.r.DataSourceCreator:62 - No connection pooling DataSource implementation found on the classpath - no pooling is in effect.

Spring 2 seems to come with a dependency or new implementation(?) which needs a specific datasource:
-  o.s.c.s.r.PooledDataSourceCreator:21 - Found DBCP2 on the classpath. Using it for DataSource connection pooling.

The postgreSQL service is tagged with "relational". I'm asking because I found that tags are scanned by spring 2.0 [1].

Regards
Morten

[1] https://github.com/cloudfoundry/java-buildpack/issues/574

**Comment by scottfrederick** [comment]
@mortenri How are you getting the Spring Cloud Connectors dependencies into your project? Do you have explicit dependencies on the Connectors libraries in your build file, or are you using Spring Boot's `spring-boot-starter-cloud-connectors`? 

With Spring Boot 2.x, you should be using Spring Cloud Connectors `2.0.x.RELEASE`. It appears to me that you might be using an older `1.x.x.RELEASE` version of Connectors. If you have explicit dependencies on Connector libs, please upgrade the versions to the latest `2.0.3.RELEASE` currently. If you are using the Boot starter then you should be getting the right version transitively, and there might be something else going on.

**Comment by mortenri** [comment]
I'm using the explicit dependency to the cloud connector:

```
 <dependency>
     <groupId>org.springframework.cloud</groupId>
     <artifactId>spring-cloud-cloudfoundry-connector</artifactId>
     </dependency>
```

The version is managed by the dependency management `spring-boot-dependencies` (version 2.0.6). I also checked the dependency tree and can only find the following version `org.springframework.cloud:spring-cloud-spring-service-connector:jar:2.0.3.RELEASE:compile`.  Also, the local integration tests are working and spring starts regularly.  The issue only appears when pushing the application to cloud foundry. Does cloud foundry need to be prepared for spring 2.x? 

regards
Morten

**Comment by scottfrederick** [comment]
@mortenri Thanks for the additional information. Based on the versions you are using, I can't see where the problem might be. Can you share the entire stracktrace for the `java.lang.NoClassDefFoundError: org/apache/commons/dbcp2/BasicDataSource` error so I can see what is attempting to load that class?

**Comment by mortenri** [comment]
Of course. Here is the full stacktrace.

```
java.lang.NoClassDefFoundError: org/apache/commons/dbcp2/BasicDataSource
    at org.springframework.cloud.service.relational.BasicDbcpPooledDataSourceCreator.create(BasicDbcpPooledDataSourceCreator.java:22)
    at org.springframework.cloud.service.relational.DataSourceCreator.createPooledDataSource(DataSourceCreator.java:74)
    at org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:57)
    at org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:26)
    at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:288)
    at org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:180)
    at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createService(AbstractCloudServiceConnectorFactory.java:105)
    at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.createInstance(AbstractCloudServiceConnectorFactory.java:99)
    at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:142)
    at org.springframework.cloud.service.AbstractCloudServiceConnectorFactory.afterPropertiesSet(AbstractCloudServiceConnectorFactory.java:94)
    at org.springframework.cloud.config.CloudScanHelper.registerServiceBean(CloudScanHelper.java:93)
    at org.springframework.cloud.config.CloudScanHelper.registerServiceBeans(CloudScanHelper.java:59)
    at org.springframework.cloud.config.java.ServiceScanConfiguration.registerBeanDefinitions(ServiceScanConfiguration.java:22)
    at org.springframework.cloud.config.java.CloudScanConfiguration.registerBeanDefinitions(CloudScanConfiguration.java:22)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:36
    at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:363)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145)
    at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
    at my.spring.app.Application.main(Application.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.dbcp2.BasicDataSource
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 40 common frames omitted
```

**Comment by scottfrederick** [comment]
@mortenri I see now what's happening here. 

When creating a `javax.sql.DataSource` bean for a connection to a relational DB, Connectors inspects the classpath for the following connection pooling datasource libraries: 

* Tomcat JDBC Connection Pool
* HikariCP
* Tomcat DBCP
* Apache Commons DBCP2

If none of the first three are found, the code assumes the fourth should be used, and throws the `java.lang.ClassNotFoundException: org.apache.commons.dbcp2.BasicDataSource` exception if DBCP2 isn't present at runtime. The code should include a check to verify that class is available before trying to use it. I'll fix that. 

I would suggest for performance reasons that you consider making one of these connection pooling libraries. Otherwise, after this change, Connectors will default to using Spring's `SimpleDriverDataSource`, which does no pooling.

**Comment by scottfrederick** [comment]
Fixed via c10b15ece320a883ef222886d7856d839fe1f288

**Comment by mortenri** [comment]
Thank you for the information and fix. We are currently not using the DataSource at all. Due to some historical reasons inject an Entity Manager on our own. We consider refactoring this piece of code.

**Comment by scottfrederick** [comment]
> We are currently not using the DataSource at all.

Ok, that makes sense. You apparently have a database service bound to the application, which causes Connectors to create a `DataSource` bean for connecting to the database even if you don't use it. Once this fix is released that shouldn't cause any harm.
