### ISSUE TITLE
Redis Service Uris in Cloud Foundry do not contain user info, thus UriBasedServiceInfo throws exception

### ISSUE THREAD

**Issue by MaikKingma** [spring-cloud/spring-cloud-connectors#293]
https://github.com/spring-cloud/spring-cloud-connectors/blob/98aa9d141d4ac6fafa22a02c61e1c9dff5ac92ae/spring-cloud-cloudfoundry-connector/src/main/java/org/springframework/cloud/cloudfoundry/RedisServiceInfoCreator.java#L26

We are trying to connect to a redis service in our spring application. although our binding provides all the neccessary info such as host port and password, it also contains a URI with all info combined which leads to the unfortunate case that the else event is triggered and the Service info is created via `return new RedisServiceInfo(id, uri);` (RedisServiceInfoCreator:32) instead of  `return new RedisServiceInfo(id, host, port, password);` RedisServiceInfoCreator:30 

In order to save a lot of custom work to overwrite UriBasedServiceInfo.getUriInfoFactory method the default service info creator should definitely be constructred via host port and password constructor and only if they are not completely provided fall back to the URI, which in case of redis definitely needs a custom UriBasedServiceInfo class.

here the stack trace that lead to our findings:

`LOGBACK:09:04:45.551 [main] ERROR o.s.boot.SpringApplication - Application startup failed
Process has crashed with type: "web"
java.lang.IllegalArgumentException: Bad userinfo in URI: redis://xxxxxxxxxxxxxxxxxxxxxxxxxxxx@xx.x.xx.xx:6379
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.parseUserinfo(UriInfo.java:133)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.<init>(UriInfo.java:58)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.StandardUriInfoFactory.createUri(StandardUriInfoFactory.java:17)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.UriBasedServiceInfo.<init>(UriBasedServiceInfo.java:26)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.RedisServiceInfo.<init>(RedisServiceInfo.java:23)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.RedisServiceInfoCreator.createServiceInfo(RedisServiceInfoCreator.java:33)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.RedisServiceInfoCreator.createServiceInfo(RedisServiceInfoCreator.java:13)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfo(AbstractCloudConnector.java:61)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfos(AbstractCloudConnector.java:40)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceInfos(Cloud.java:89)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getCloudProperties(Cloud.java:256)
    at org.cloudfoundry.reconfiguration.CloudPropertySourceApplicationContextInitializer.lambda$initialize$1(CloudPropertySourceApplicationContextInitializer.java:50)
    at org.cloudfoundry.reconfiguration.AbstractCloudHolder.withCloud(AbstractCloudHolder.java:41)
    at org.cloudfoundry.reconfiguration.CloudPropertySourceApplicationContextInitializer.initialize(CloudPropertySourceApplicationContextInitializer.java:47)
    at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567)
    at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
    at de.xxxxxxx.Application.main(Application.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)`

**Comment by scottfrederick** [comment]
This should be fixed via #295
