### ISSUE TITLE
Singleton RabbitMQ

### ISSUE THREAD

**Issue by codecandy2015** [spring-cloud/spring-cloud-connectors#99]
Hi,
I am trying to bind and use RabbitMQ in a simple Jersey application in plain java. I have RabbitMQ Installed in my local machine and I am able to communicate and exchange messages over the broker.

I am trying to use the same ove CF using Spring libs like this:-

```java
// Set up for Cloud foundry
		ConnectionFactory cloudFactory = new CachingConnectionFactory();
		AmqpAdmin admin = new RabbitAdmin(cloudFactory);
		admin.declareQueue(new Queue("rabbitdemo"));
		AmqpTemplate template = new RabbitTemplate(cloudFactory);
		template.convertAndSend("rabbitdemo", message); 
```

I am naming my service id as "rabbitdemo". When I try to send this message, I get an error:-
```java
org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused
Exception in thread "Thread-5" org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused
	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:54)
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:207)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:441)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$1.createConnection(ConnectionFactoryUtils.java:80)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:67)
	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:130)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1036)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1029)
	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1005)
	at com.sap.iot.demo.messaging.SpringNotificationProducer.run(SpringNotificationProducer.java:36)
	at org.springframework.amqp.rabbit.core.RabbitAdmin.declareQueue(RabbitAdmin.java:148)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
```
Is there anything I am doing wrong or is this the right way to use RabbitMQ using Spring !? Any help would be appreciated.
thanks
Domnic

**Comment by codecandy2015** [comment]
UPDATE:- 
I got this working by setting the connection URI. I had the connection refused as my credentials were not passed on. Now the producer is working with the following:-

```java
try{
			// Set up for Cloud foundry
			ConnectionFactory rmqFactory = (ConnectionFactory) new com.rabbitmq.client.ConnectionFactory();
			rmqFactory.setUri("amqp://joqwkalpha:Omw-mypassword-bAVTtwfx@turtle.rmq.cloudamqp.com/joqwkalpha");
			CachingConnectionFactory cloudFactory = new CachingConnectionFactory(rmqFactory); 
			RabbitTemplate template = new RabbitTemplate(cloudFactory); 
			log.info("Producing message: creating template");
			MessageProperties props = MessagePropertiesBuilder.newInstance()
					.setContentType(MessageProperties.CONTENT_TYPE_TEXT_PLAIN)
					.build();
			log.info("Producing message: creating msg properties");
				Message msg = MessageBuilder.withBody(this.message.getBytes())
					.andProperties(props)
					.build(); 
			log.info("Producing message: creating message");
			template.send(EXCHANGE_NAME, ROUTING_KEY, msg); 
			log.info("Producing message: S E N T"); 
			cloudFactory.setCloseTimeout(cloudFactory.DEFAULT_CLOSE_TIMEOUT);
		} catch (Exception ex) {
			log.severe("Producing message: error " + ex.getLocalizedMessage());
		} finally {
			
		}
´´´

With this I am able to send my message. I am trying to receive them by polling. I am able to connect the same way as the producer. However, when I try:-

```java
try {
			 
				// Set up for Cloud foundry
				ConnectionFactory rmqFactory = (ConnectionFactory) new com.rabbitmq.client.ConnectionFactory();
				rmqFactory.setUri("amqp://joqwkalpha-bAVTtwfx@turtle.rmq.cloudamqp.com/joqwkalpha");
				CachingConnectionFactory cloudFactory = new CachingConnectionFactory(rmqFactory);
				 
				RabbitTemplate template = new RabbitTemplate(cloudFactory); 
				template.setExchange(EXCHANGE_NAME);
while (!terminateListen) {

				try {
					log.info("Waiting here....: RX message" + System.currentTimeMillis());
					Object message = template.receiveAndConvert(ROUTING_KEY);
							
					
					if (message instanceof String) {
						log.info("Consuming message: String message");
						String strMessage = (String) message;
						setMessage(strMessage); 
						terminateListen = true;
						
					}
.......
}

```

I am always getting a null.. even after producing a message from my sender. Is there something I need to consider while receiving the data ?

thanks
Dom

**Comment by dsyer** [comment]
By the end of that you don't have any Spring Cloud code in there. Maybe this is a generic Spring AMQP question (Stackoverflow might be better for that)?

**Comment by garyrussell** [comment]
You don't show your ROUTING_KEY or EXCHANGE_NAME values.

Your described use case will only work if the EXCHANGE_NAME is `""` and ROUTING_KEY is the queue name.

Setting the EXCHANGE_NAME on the receiving template does nothing. We send to exchanges (with a routing key) and receive from queues (bound to exchanges with some routing key).

**Comment by scottfrederick** [comment]
@codecandy2015 As @dsyer said above, it does not appear that there is any Spring Cloud Connectors code involved in this issue, so it may not belong in this GitHub repo. Can we close this issue and have you ask the question in StackOverflow (using the `spring amqp` or `spring rabbitmq` tag)?
